---
name: "Bug Report"
description: "Report a bug to be fixed."
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🪳 Bug Report
        Thanks for taking the time to report a bug!  
        Please ensure you're running the **latest version** before submitting.  

  - type: input
    id: bug-title
    attributes:
      label: "Bug Title"
      description: "Provide a short and clear title for the bug."
      placeholder: "e.g. Crash when opening settings"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the exact steps to recreate the bug."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what should have happened instead."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happened."
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: "Operating System"
      description: "Which OS are you using?"
      options:
        - Windows 10
        - Windows 11
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Software Version"
      description: "Which version of the program are you using?"
      placeholder: "e.g. v1.2.3"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Error Message or Logs"
      description: "Paste any error messages or logs related to the issue."
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any extra details or relevant information?"
    validations:
      required: false

  - type: checkboxes
    id: latest-version-check
    attributes:
      label: "Latest Version Confirmation"
      description: "Please confirm that you've tested on the latest version."
      options:
        - label: "I have tested this on the latest version, and the bug still occurs."
          required: true
