---
name: "Request Feature"
description: "Request a feature that isn't in development yet or planned."
---

**Feature Description**
- **Feature Title**: [e.g. Name input]
- **Description**: [e.g. Allow the user to input their name]
